spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: bank
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${DB_USER:bank}
    password: ${DB_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      jdbc:
        time_zone: UTC
      # Necesario para que Hibernate acepte TIMESTAMPTZ mapeado a Instant sin warnings
      type:
        preferred_instant_jdbc_type: TIMESTAMP_WITH_TIMEZONE


    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}

app:
  auth:
    token: ${APP_AUTH_TOKEN:dev-token-change-me}
  timezone:
    business: America/Mexico_City